Fix Python 2.7
/python2.7/site-packages/psautohint/autohint.py:442: in hintFiles
    hintFile(options, options.reference_font, None, reference_master=True)
/python2.7/site-packages/psautohint/autohint.py:623: in hintFile
    fontData.save(outpath)
/python2.7/site-packages/psautohint/ufoFont.py:447: in save
    glyphset = writer.getGlyphSet(layer, defaultLayer=layer is None)
/python2.7/site-packages/fontTools/ufoLib/__init__.py:1387: in getGlyphSet
    return self._getGlyphSetFormatVersion3(validateRead, validateWrite, layerName=layerName, defaultLayer=defaultLayer, glyphNameToFileNameFunc=glyphNameToFileNameFunc)
/python2.7/site-packages/fontTools/ufoLib/__init__.py:1449: in _getGlyphSetFormatVersion3
    glyphSubFS = self.fs.makedir(directory, recreate=True)
/python2.7/site-packages/fs/osfs.py:311: in makedir
    _path = self.validatepath(path)
TypeError: paths must be unicode (not str)