Revert "No need to include the headers manually"
actually, that's not true.
We still need to include *.h in the MANIFEST otherwise I get this when
building from a sdist zip:

python/psautohint/_psautohint.c:33:10: fatal error: 'psautohint.h' file not found

This reverts commit 0cbe820faf45f878ef4357696ef8968ec405aea2.